name: Release Proper
on:
  push:
    tags:
      - '*.*.*-**'
  workflow_dispatch:

jobs:
  prerequisites:
    name: prerequisites
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
    - run: dotnet build --configuration Release 
    - name: Create the package
      run: dotnet pack --configuration Release -o artifacts /p:Version=${{ github.ref_name }}
    - name: Publish the package to GPR
      run: dotnet nuget push artifacts/*.nupkg
